---
title: "Biostat625_finalproject"
author: "Zehua Wang, Ziman Jiang, Faye Fang, Yue Pan"
date: "12/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
bike_data = read.csv('data/SeoulBikeData.csv')
head(bike_data)
# Date : year-month-day
# Rented Bike count - Count of bikes rented at each hour
# Hour - Hour of he day
# Temperature-Temperature in Celsius
# Humidity - %
# Windspeed - m/s
# Visibility - 10m
# Dew point temperature - Celsius
# Solar radiation - MJ/m2
# Rainfall - mm
# Snowfall - cm
# Seasons - Winter, Spring, Summer, Autumn
# Holiday - Holiday/No holiday
# Functional Day - NoFunc(Non Functional Hours), Fun(Functional hours)
```

```{r}
head(bike_data)
dim(bike_data)
```
```{r}
# add year, month, day, and days of week
# notice that 
bike_data$Date = as.Date(bike_data$Date, "%d/%m/%Y")
bike_data$Year = factor(format(bike_data$Date, "%Y"))
bike_data$Month = factor(months(bike_data$Date))
bike_data$Day = factor(format(bike_data$Date, "%d"))
bike_data$DWeek = factor(weekdays(bike_data$Date))
#rename
colnames(bike_data) <- c('Date','Rented_Bike_Count', 'Hour', 'Temperature',
                         'Humidity', 'Wind_speed', 'Visibility', 'Dew_point_temp',
                         'Solar_Rad', 'Rainfall', 'Snowfall', 'Seasons', 
                         'Holiday', 'Funct_Day','Year', 'Month', 'Day', 'DWeek')
head(bike_data)
```

```{r}
library(ggplot2)
library(hrbrthemes)
library(ggthemes) 
# Plot Average count by week 
ggplot(bike_data, aes(x=DWeek, y=Rented_Bike_Count ,fill= DWeek))+
  geom_bar(stat = "identity") +
  ggtitle("Average Count by Week")+
  xlab("Day of Week") + 
  ylab("Rent count")  + 
  labs(fill = "Day of Week") + 
  theme_stata() +
  scale_color_stata() +
  theme(plot.title = element_text(hjust = 0.5),legend.position = "None")
# Plot Average count by month
ggplot(bike_data, aes(x=Month, y=Rented_Bike_Count ,fill= Month))+
  geom_bar(stat = "identity") +
  ggtitle("Average Count by Month")+
  xlab("Month") + 
  ylab("Rent count")  + 
  labs(fill = "Month") + 
  theme_stata() +
  scale_color_stata() +
  theme(plot.title = element_text(hjust = 0.5),legend.position = "None",axis.text.x = element_text(angle=-25))
```

```{r}
# plot Bike Count vs Hour, group by weekdays, month, season, year
ggplot(data=bike_data, aes(x = Hour, y = Rented.Bike.Count, colour = Seasons)) +
   stat_summary(geom = "line", fun.y = mean)+
   stat_summary(geom = "point", fun.y = mean)
ggplot(data=bike_data, aes(x = Hour, y = Rented.Bike.Count, colour = DWeek)) +
   stat_summary(geom = "line", fun.y = mean)+
   stat_summary(geom = "point", fun.y = mean)
ggplot(data=bike_data, aes(x = Hour, y = Rented.Bike.Count, colour = Month)) +
   stat_summary(geom = "line", fun.y = mean)+
   stat_summary(geom = "point", fun.y = mean)
ggplot(data=bike_data, aes(x = Hour, y = Rented.Bike.Count, colour = Year)) +
   stat_summary(geom = "line", fun.y = mean)+
   stat_summary(geom = "point", fun.y = mean)
```

```{r}
#plot correlation
library(corrplot)
library(RColorBrewer)
my_data <- bike_data[, 2:11]
colnames(my_data)[c(1,3:10)] <- c('Count', 'Temp', 'Humiditity', 'Wind', 'Visb', 'Dew', 'Solar','Rain','Snow')
M <-cor(my_data)
corrplot(M, method = "color", type = "upper", 
          addCoef.col = "black",number.cex=0.75, tl.col = "darkblue",
         diag = FALSE,col=brewer.pal(n=8, name="RdYlBu"), tl.srt = 30)
```

```{r}
library(Boruta)
bike_data <- bike_data[, -1]
boruta.train <- Boruta(Rented.Bike.Count~.,data=bike_data, doTrace = 2)
 plot(boruta.train, xlab = "", xaxt = "n")
 lz<-lapply(1:ncol(boruta.train$ImpHistory),function(i)
boruta.train$ImpHistory[is.finite(boruta.train$ImpHistory[,i]),i])
 names(lz) <- colnames(boruta.train$ImpHistory)
 Labels <- sort(sapply(lz,median))
 axis(side = 1,las=2,labels = names(Labels),
at = 1:ncol(boruta.train$ImpHistory), cex.axis = 0.7)
```
```{r}
## split data into a train and test set
index <- 1:nrow(bike_data)
testindex <- sample(index, trunc(length(index)*0.2))
testset <- bike_data[testindex,-1]
trainset <- bike_data[-testindex,-1]
```
